name = "sweetboss12512/rbx_profile"
version = "2.0.0"
license = "MIT"

[target]
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
lune-path = { name = "jiwonz/pathfs", version = "0.2.3" }
