[plugins]
jolemtools = 7555657789
mbtools = 6724254977
mbreflect = 11973409942
rojo = "RojoManagedPlugin"

[profiles.wos]
_desc = "Waste of space model building"
enabled = [
    "mbtools",
    "mbreflect",
]

[profiles.ss]
_desc = "Scarlet skies building"
enabled = [
    "jolemtools"
]
