[plugins]
# jolemtools = 7555657789
mbtools = 6724254977
# fail = 1
# mbreflect = 11973409942
# rojo = "RojoManagedPlugin"

[profiles.default]
enabled = [
    "rojo"
]

[profiles.wos]
description = "Waste of space model building"
enabled = [
    "mbtools",
    # "mbreflect",
]

[profiles.ss]
description = "Scarlet skies building"
enabled = [
    "jolemtools"
]
