# [config]
# pluginsFolder = "/home/sweet/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefixes/studio/drive_c/users/sweet/AppData/Local/Roblox/Plugins/"

[plugins]
jolemtools = 7555657789
mbtools = 6724254977
mbreflect = 11973409942
rojo = "RojoManagedPlugin.rbxm"

[profiles.default]
enabled = [
    "rojo"
]

[profiles.wos]
description = "Waste of space model building"
enabled = [
    "mbtools",
    "mbreflect",
]

[profiles.ss]
description = "Scarlet skies building"
enabled = [
    "jolemtools"
]
