[plugins]
jolemtools = 7555657789
mbtools = 6724254977
mbreflect = 11973409942
rojo = "RojoManagedPlugin"

# [profiles.default]
# all = true

[profiles.wos]
mbtools = true
jolemtools = false
rojo = false
_desc = "Waste of space model building"

[profiles.ss]
_desc = "Scarlet skies building"
rojo = false
mbtools = false
mbreflect = false
jolemtools = true
